### ISSUE TITLE
Can't delete connect_power.aif in Catalina

### ISSUE THREAD

**Issue by rzero1** [artginzburg/powerchime#1]
My system will not let me move or delete connect_power.aif, even with SIP disabled...

**Comment by excenter** [comment]
good news! with SIP disabled, you can just mount the OS disk as user writable 
`sudo mount -uw /\n` 
bad news! I replaced that file with an empty one manually, and it is absolutely silent in "normal conditions" (plugging/unplugging the machine) but in the problem i'm trying to solve (it sitting connected to a USB PD monitor and just dinging all night long for no reason) it still has that damned sound. 
hope this helps.

**Comment by iduaum** [comment]
Why would anyone need to delete it when Art's script completely disabled PowerChime?  Thank you @artginzburg for your work on this script!!!
